#ifndef __FGPU_INTERNAL_BUILD_CONFIG_HPP__
#define __FGPU_INTERNAL_BUILD_CONFIG_HPP__

/* Variables definition exported from CMake */
#define FGPU_COMP_COLORING_ENABLE
#define FGPU_MEM_COLORING_ENABLED
/* #undef FGPU_USER_MEM_COLORING_ENABLED */
#define FGPU_TEST_MEM_COLORING_ENABLED
/* #undef FGPU_PARANOID_CHECK_ENABLED */
/* #undef FGPU_COMPUTE_CHECK_ENABLED */
/* #undef FGPU_SERIALIZED_LAUNCH */

#endif // __FGPU_INTERNAL_BUILD_CONFIG_HPP__
